ARG base_image
FROM ${base_image}

RUN echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y iptables ipset && \
    apt-get -t buster-backports install -y wireguard

RUN go get gotest.tools/gotestsum
